name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0 # Laatste versie van google_maps_flutter
  youtube_player_flutter: ^9.1.1 
  flutter_inappwebview: ^6.0.0
  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/app_logo.png

flutter_launcher_icons:
  android: true
  ios: true # Optioneel, als je ook iOS wilt ondersteunen
  image_path: "assets/images/app_logo.png"